version: '3.8'
services:
  s-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: ${TARGETARCH:-amd64}
    platform: linux/${TARGETARCH:-amd64}
    container_name: s-ui
    ports:
      - "2095:2095"
      - "2096:2096"
      - "80:80"
      - "443:443"
    volumes:
      - ./db:/usr/local/s-ui/db
      - ./cert:/root/cert
    restart: unless-stopped
